name: "pma"
version: "1.0.0"
config-version: 2
profile: pma
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["dbt_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
models:
  +materialized: table
  pma:
    +file_format: parquet
    staging:
      +schema: staging
    standardized:
      +schema: standardized
    curated:
      +schema: curated
seeds:
  # Globally quote all seed columns
  # https://docs.getdbt.com/reference/resource-configs/quote_columns
  +quote_columns: true
  pma:
    +schema: seed
    jpn_national_holidays:
      +column_types:
        holiday_date: date
    jepx_areas:
      +column_types:
        area_key: int
    jma_stations:
      +column_types:
        prefecture_code: int
        latitude: double
        longitude: double
        elevation_m: double
        # keep as string: the mask can have leading zeros
        kansoku: string
        obs_precipitation: int
        obs_wind: int
        obs_temperature: int
        obs_sunshine: int
        obs_snow: int
        obs_other: int
        observation_ended_on: date
