"""Feast feature views over the dbt feature marts.

GENERATED by scripts/generate_feature_views.py from dbt/target/manifest.json;
do not edit. Regenerate with `just feature-views` after a mart changes.
"""

from feast import FeatureView, Field
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
from feast.types import Float64, Int64

from power_market_analytics.features.entities import GRAIN_ENTITIES

FTR_DAY_CALENDAR_SOURCE = SparkSource(
    name="ftr_day_calendar",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, month, day_of_week, day_type, holiday_degree, half, quarter, day_of_month, day_of_quarter, day_of_year, is_business_day, fiscal_quarter, days_since_holiday, days_until_holiday, available_at from pma_features.ftr_day_calendar",
    timestamp_field="available_at",
    description="Calendar features of every delivery day for every bidding zone: dim_date's attributes as the demand strategies read them (research demand/R-003 and R-005) plus the two distances in days to the nearest named holiday. Grain: area_code x trade_date. The values do not depend on the area; the key is there so every feature mart joins on the same keys. Feature columns carry config.meta.feature; keys and available_at do not.",
)
FTR_DAY_CALENDAR = FeatureView(
    name="ftr_day_calendar",
    entities=list(GRAIN_ENTITIES["day"]),
    schema=[
        Field(
            name="month",
            dtype=Int64,
            description="Calendar month 1-12: the strategies' month feature.",
            tags={"categorical": "false"},
        ),
        Field(
            name="day_of_week",
            dtype=Int64,
            description="Day of week with Monday = 0 and Sunday = 6, pandas dayofweek, as the strategies use it (dim_date.day_of_week_iso - 1).",
            tags={"categorical": "false"},
        ),
        Field(
            name="day_type",
            dtype=Int64,
            description="0 Weekday, 1 Weekend, 2 Holiday; a holiday wins over the weekend flag (research demand/R-003). A LightGBM categorical.",
            tags={"categorical": "true"},
        ),
        Field(
            name="holiday_degree",
            dtype=Float64,
            description="dim_date.holiday_degree, the graded 休日度合い from 0 to 1 (research demand/R-005).",
            tags={"categorical": "false"},
        ),
        Field(
            name="half",
            dtype=Int64,
            description="dim_date.half: 1 before July, else 2.",
            tags={"categorical": "false"},
        ),
        Field(
            name="quarter",
            dtype=Int64,
            description="dim_date.quarter, calendar quarter 1-4.",
            tags={"categorical": "false"},
        ),
        Field(
            name="day_of_month",
            dtype=Int64,
            description="dim_date.day_of_month.",
            tags={"categorical": "false"},
        ),
        Field(
            name="day_of_quarter",
            dtype=Int64,
            description="dim_date.day_of_quarter.",
            tags={"categorical": "false"},
        ),
        Field(
            name="day_of_year",
            dtype=Int64,
            description="dim_date.day_of_year.",
            tags={"categorical": "false"},
        ),
        Field(
            name="is_business_day",
            dtype=Int64,
            description="dim_date.is_business_day as 1 / 0: a working day, not a bank day.",
            tags={"categorical": "false"},
        ),
        Field(
            name="fiscal_quarter",
            dtype=Int64,
            description="dim_date.fiscal_quarter, April = Q1.",
            tags={"categorical": "false"},
        ),
        Field(
            name="days_since_holiday",
            dtype=Int64,
            description="Calendar days since the nearest earlier named holiday (dim_date.is_holiday), 0 on a holiday; null before the spine's first holiday.",
            tags={"categorical": "false"},
        ),
        Field(
            name="days_until_holiday",
            dtype=Int64,
            description="Calendar days until the nearest later named holiday, 0 on a holiday; null after the spine's last holiday.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_DAY_CALENDAR_SOURCE,
    online=False,
    description="Calendar features of every delivery day for every bidding zone: dim_date's attributes as the demand strategies read them (research demand/R-003 and R-005) plus the two distances in days to the nearest named holiday. Grain: area_code x trade_date. The values do not depend on the area; the key is there so every feature mart joins on the same keys. Feature columns carry config.meta.feature; keys and available_at do not.",
    tags={"grain": "day"},
)

FTR_DAY_OCCTO_SOURCE = SparkSource(
    name="ftr_day_occto",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, max_demand_hour_ending, max_demand_mw, max_supply_capacity_mw, available_at from pma_features.ftr_day_occto",
    timestamp_field="available_at",
    description="The OCCTO 翌々日 peak forecast of each delivery day per bidding zone, the three fields the spot-price lightgbm_occto strategy uses (research spot_price/R-001). Grain: area_code x trade_date, from 2024-04-01. available_at is the fact's: 18:00 on D-2.",
)
FTR_DAY_OCCTO = FeatureView(
    name="ftr_day_occto",
    entities=list(GRAIN_ENTITIES["day"]),
    schema=[
        Field(
            name="max_demand_hour_ending",
            dtype=Int64,
            description="Hour ending 1-24 of the forecast peak demand.",
            tags={"categorical": "false"},
        ),
        Field(
            name="max_demand_mw",
            dtype=Int64,
            description="Forecast peak demand, MW.",
            tags={"categorical": "false"},
        ),
        Field(
            name="max_supply_capacity_mw",
            dtype=Int64,
            description="Forecast supply capacity at the peak, MW.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_DAY_OCCTO_SOURCE,
    online=False,
    description="The OCCTO 翌々日 peak forecast of each delivery day per bidding zone, the three fields the spot-price lightgbm_occto strategy uses (research spot_price/R-001). Grain: area_code x trade_date, from 2024-04-01. available_at is the fact's: 18:00 on D-2.",
    tags={"grain": "day"},
)

FTR_HOUR_JMA_OBS_SOURCE = SparkSource(
    name="ftr_hour_jma_obs",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, hour_ending, wavg_temperature_c, available_at from pma_features.ftr_hour_jma_obs",
    timestamp_field="available_at",
    description="The recency-weighted same-hour temperature at each bidding zone's representative JMA station (dim_area.representative_jma_station_id) over D-8..D-2, the demand presets' wavg_temperature_c. Grain: area_code x trade_date x hour_ending (1-24, hour ending). A row exists for every delivery day that at least one lag observation reaches; the value is null only when every lag is missing.",
)
FTR_HOUR_JMA_OBS = FeatureView(
    name="ftr_hour_jma_obs",
    entities=list(GRAIN_ENTITIES["hour"]),
    schema=[
        Field(
            name="wavg_temperature_c",
            dtype=Float64,
            description="Weighted mean of the station's temperature at this hour on D-2..D-8, weight 0.5 ** (k - 2) for lag k, renormalised over the lags present; null when all are missing. The terms are added in lag order (D-2 first), so the value is the same on every build (the ordered_weighted_mean macro).",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_HOUR_JMA_OBS_SOURCE,
    online=False,
    description="The recency-weighted same-hour temperature at each bidding zone's representative JMA station (dim_area.representative_jma_station_id) over D-8..D-2, the demand presets' wavg_temperature_c. Grain: area_code x trade_date x hour_ending (1-24, hour ending). A row exists for every delivery day that at least one lag observation reaches; the value is null only when every lag is missing.",
    tags={"grain": "hour"},
)

FTR_HOUR_MSM_SOURCE = SparkSource(
    name="ftr_hour_msm",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, hour_ending, forecast_temperature_c, popw_forecast_temperature_c, popw_forecast_relative_humidity_pct, popw_forecast_precipitation_mm, available_at from pma_features.ftr_hour_msm",
    timestamp_field="available_at",
    description="The MSM forecast for each delivery-day hour per bidding zone, one row per forecast vintage: the representative station's temperature (the demand lightgbm_msm feature) and the population-weighted temperature, humidity and rain over the area's staffed stations with the latest census vintage's weights (lightgbm_msm_popw and the similar-day selector; tasks/demand/datasets.py). Grain: area_code x trade_date x hour_ending x forecast_reference_at. available_at is the vintage's: reference + 4 h.",
)
FTR_HOUR_MSM = FeatureView(
    name="ftr_hour_msm",
    entities=list(GRAIN_ENTITIES["hour"]),
    schema=[
        Field(
            name="forecast_temperature_c",
            dtype=Float64,
            description="Forecast temperature at the area's representative station, C.",
            tags={"categorical": "false"},
        ),
        Field(
            name="popw_forecast_temperature_c",
            dtype=Float64,
            description="Population-weighted forecast temperature over the area's stations, C, renormalised over the stations that have a value; the terms are added in station order, so the value is the same on every build (the ordered_weighted_mean macro).",
            tags={"categorical": "false"},
        ),
        Field(
            name="popw_forecast_relative_humidity_pct",
            dtype=Float64,
            description="Population-weighted forecast relative humidity, %, renormalised over the stations that have a value and added in station order.",
            tags={"categorical": "false"},
        ),
        Field(
            name="popw_forecast_precipitation_mm",
            dtype=Float64,
            description="Population-weighted forecast precipitation over the hour, mm, renormalised over the stations that have a value and added in station order.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_HOUR_MSM_SOURCE,
    online=False,
    description="The MSM forecast for each delivery-day hour per bidding zone, one row per forecast vintage: the representative station's temperature (the demand lightgbm_msm feature) and the population-weighted temperature, humidity and rain over the area's staffed stations with the latest census vintage's weights (lightgbm_msm_popw and the similar-day selector; tasks/demand/datasets.py). Grain: area_code x trade_date x hour_ending x forecast_reference_at. available_at is the vintage's: reference + 4 h.",
    tags={"grain": "hour"},
)

FTR_PERIOD_ACTUALS_SOURCE = SparkSource(
    name="ftr_period_actuals",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, time_code, lag_7d_demand_kwh, available_at from pma_features.ftr_period_actuals",
    timestamp_field="available_at",
    description="The area demand seven days before each delivery period, the demand strategies' lag_7d_demand_kwh, from fct_area_demand_generation_actual. Grain: area_code x trade_date x time_code. A period whose D-7 actual is a TSO hole has no row. available_at is the D-7 row's.",
)
FTR_PERIOD_ACTUALS = FeatureView(
    name="ftr_period_actuals",
    entities=list(GRAIN_ENTITIES["period"]),
    schema=[
        Field(
            name="lag_7d_demand_kwh",
            dtype=Int64,
            description="Area demand over the same period on D-7, kWh.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_PERIOD_ACTUALS_SOURCE,
    online=False,
    description="The area demand seven days before each delivery period, the demand strategies' lag_7d_demand_kwh, from fct_area_demand_generation_actual. Grain: area_code x trade_date x time_code. A period whose D-7 actual is a TSO hole has no row. available_at is the D-7 row's.",
    tags={"grain": "period"},
)

FTR_PERIOD_JEPX_SOURCE = SparkSource(
    name="ftr_period_jepx",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, time_code, lag_1d_price, available_at from pma_features.ftr_period_jepx",
    timestamp_field="available_at",
    description="The area spot price one day before each delivery period, the spot-price strategies' lag_1d_price, from fct_jepx_spot_area_price. Grain: area_code x trade_date x time_code. A period whose D-1 price is null (Hokkaido 2018-09) has no row. available_at is the D-1 row's: D-2 12:00.",
)
FTR_PERIOD_JEPX = FeatureView(
    name="ftr_period_jepx",
    entities=list(GRAIN_ENTITIES["period"]),
    schema=[
        Field(
            name="lag_1d_price",
            dtype=Float64,
            description="Area price of the same period on D-1, JPY/kWh.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_PERIOD_JEPX_SOURCE,
    online=False,
    description="The area spot price one day before each delivery period, the spot-price strategies' lag_1d_price, from fct_jepx_spot_area_price. Grain: area_code x trade_date x time_code. A period whose D-1 price is null (Hokkaido 2018-09) has no row. available_at is the D-1 row's: D-2 12:00.",
    tags={"grain": "period"},
)

FTR_PERIOD_SIMILAR_DAY_SOURCE = SparkSource(
    name="ftr_period_similar_day",
    query="select area_code, cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key, time_code, similar_day_demand_kwh, available_at, published_at from pma_features.ftr_period_similar_day",
    timestamp_field="available_at",
    created_timestamp_column="published_at",
    description="The load of a learned similar day one year earlier for every delivery period, the demand similar-day feature (research demand/R-004 E-002), as scripts/fit_similar_day.py scored it walking forward and wrote it to pma_ml.similar_day. Every few days the job refits the seven weights of tasks/demand/similar_day.py's distance on the 730 days before that step and scores the days that follow with them: for a delivery day D the nearest day in D - 364 +- 30 (days from D - 364, the 24-hour RMSE of D's population-weighted MSM forecast against the candidate's population-weighted observation for temperature, humidity and rain, the differences in days since and until a named holiday and in holiday degree), its hourly load over the hour containing the period halved. No day is scored with weights that saw a load that was not yet public: each fit runs at a cutoff on the pairs of the 730 days before it whose target load was public by then, a day is scored by the latest fit whose cutoff is on or before its issue time, and available_at is the latest of D's MSM forecast vintage's, that cutoff and the chosen day's load availability. The chosen day, its lag, its distance, the candidate count and the fit's cutoff sit next to the feature, untagged. One row per scoring run: the as-of join takes the newest run usable at the issue time, and among rows tied on available_at the newest published wins, so a re-run replaces the feature wherever it scored. Grain: area_code x trade_date x time_code x similar_day_run_id.",
)
FTR_PERIOD_SIMILAR_DAY = FeatureView(
    name="ftr_period_similar_day",
    entities=list(GRAIN_ENTITIES["period"]),
    schema=[
        Field(
            name="similar_day_demand_kwh",
            dtype=Float64,
            description="The chosen similar day's hourly load (fct_area_power_usage_hourly, kWh over the hour containing the period) halved, kWh per 30-minute period.",
            tags={"categorical": "false"},
        ),
    ],
    source=FTR_PERIOD_SIMILAR_DAY_SOURCE,
    online=False,
    description="The load of a learned similar day one year earlier for every delivery period, the demand similar-day feature (research demand/R-004 E-002), as scripts/fit_similar_day.py scored it walking forward and wrote it to pma_ml.similar_day. Every few days the job refits the seven weights of tasks/demand/similar_day.py's distance on the 730 days before that step and scores the days that follow with them: for a delivery day D the nearest day in D - 364 +- 30 (days from D - 364, the 24-hour RMSE of D's population-weighted MSM forecast against the candidate's population-weighted observation for temperature, humidity and rain, the differences in days since and until a named holiday and in holiday degree), its hourly load over the hour containing the period halved. No day is scored with weights that saw a load that was not yet public: each fit runs at a cutoff on the pairs of the 730 days before it whose target load was public by then, a day is scored by the latest fit whose cutoff is on or before its issue time, and available_at is the latest of D's MSM forecast vintage's, that cutoff and the chosen day's load availability. The chosen day, its lag, its distance, the candidate count and the fit's cutoff sit next to the feature, untagged. One row per scoring run: the as-of join takes the newest run usable at the issue time, and among rows tied on available_at the newest published wins, so a re-run replaces the feature wherever it scored. Grain: area_code x trade_date x time_code x similar_day_run_id.",
    tags={"grain": "period"},
)

#: Every feature view, by mart name.
VIEWS = (
    FTR_DAY_CALENDAR,
    FTR_DAY_OCCTO,
    FTR_HOUR_JMA_OBS,
    FTR_HOUR_MSM,
    FTR_PERIOD_ACTUALS,
    FTR_PERIOD_JEPX,
    FTR_PERIOD_SIMILAR_DAY,
)
