"""Write the Feast feature views of the dbt feature marts from the dbt manifest.

Every model under ``models/features/`` becomes one ``SparkSource`` (a query
selecting its keys, ``trade_date_key``, its tagged feature columns and
``available_at``) and one ``FeatureView`` on the entities of its grain. The
output is ``power_market_analytics/features/views.py``; ``--check`` exits 1
when that file is stale, which the ``dbt parse`` CI job runs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "dbt" / "target" / "manifest.json"
DEFAULT_OUTPUT = REPO_ROOT / "power_market_analytics" / "features" / "views.py"
FEATURES_PATH_PREFIX = "features/"
#: dbt contract data types → Feast types.
DTYPES: dict[str, str] = {
    "int": "Int64",
    "bigint": "Int64",
    "double": "Float64",
    "string": "String",
    "boolean": "Bool",
    "timestamp": "UnixTimestamp",
}
TRADE_DATE_KEY_SQL = "cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key"
HEADER = '''"""Feast feature views over the dbt feature marts.

GENERATED by scripts/generate_feature_views.py from dbt/target/manifest.json;
do not edit. Regenerate with `just feature-views` after a mart changes.
"""

from feast import FeatureView, Field
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
from feast.types import {types}

from power_market_analytics.features.entities import GRAIN_ENTITIES
'''


def literal(text: str) -> str:
    """A double-quoted Python string literal for ``text`` (JSON escaping is a subset of Python's).

    Parameters
    ----------
    text : str

    Returns
    -------
    str
    """
    return json.dumps(text, ensure_ascii=False)


def feature_models(manifest: dict) -> list[dict]:
    """The manifest's models under ``models/features/``, by name.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    list of dict
    """
    return sorted(
        (
            node
            for node in manifest["nodes"].values()
            if node["resource_type"] == "model" and node["path"].startswith(FEATURES_PATH_PREFIX)
        ),
        key=lambda node: node["name"],
    )


def column_meta(column: dict) -> dict:
    """A column's ``meta`` (dbt 1.10 keeps it under ``config``, older manifests at the top).

    Parameters
    ----------
    column : dict

    Returns
    -------
    dict
    """
    return column.get("config", {}).get("meta") or column.get("meta") or {}


def grain_of(node: dict) -> str:
    """``period`` when the mart has ``time_code``, ``hour`` when ``hour_ending``, else ``day``.

    Parameters
    ----------
    node : dict
        A manifest model node.

    Returns
    -------
    str
    """
    columns = node["columns"]
    if "time_code" in columns:
        return "period"
    if "hour_ending" in columns:
        return "hour"
    return "day"


def render(manifest: dict) -> str:
    """The ``views.py`` module text for the manifest's feature marts.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        If a tagged feature column has a data type without a Feast type.
    """
    used_types: set[str] = set()
    blocks: list[str] = []
    names: list[str] = []
    for node in feature_models(manifest):
        name = node["name"]
        grain = grain_of(node)
        keys = ["area_code", TRADE_DATE_KEY_SQL] + (
            ["time_code"] if grain == "period" else ["hour_ending"] if grain == "hour" else []
        )
        fields: list[str] = []
        feature_cols: list[str] = []
        for column in node["columns"].values():
            meta = column_meta(column)
            if not meta.get("feature"):
                continue
            dtype = DTYPES.get(column["data_type"])
            if dtype is None:
                raise ValueError(
                    f"{name}.{column['name']}: data type {column['data_type']!r} has no Feast type"
                )
            used_types.add(dtype)
            feature_cols.append(column["name"])
            categorical = "true" if meta.get("categorical") else "false"
            fields.append(
                "        Field(\n"
                f"            name={literal(column['name'])},\n"
                f"            dtype={dtype},\n"
                f"            description={literal(column.get('description', '').strip())},\n"
                f'            tags={{"categorical": {literal(categorical)}}},\n'
                "        ),\n"
            )
        query = (
            "select "
            + ", ".join([*keys, *feature_cols, "available_at"])
            + f" from {node['schema']}.{name}"
        )
        const = name.upper()
        blocks.append(
            f"\n{const}_SOURCE = SparkSource(\n"
            f"    name={literal(name)},\n"
            f"    query={literal(query)},\n"
            '    timestamp_field="available_at",\n'
            f"    description={literal(node.get('description', '').strip())},\n"
            ")\n"
            f"{const} = FeatureView(\n"
            f"    name={literal(name)},\n"
            f"    entities=list(GRAIN_ENTITIES[{literal(grain)}]),\n"
            "    schema=[\n" + "".join(fields) + "    ],\n"
            f"    source={const}_SOURCE,\n"
            "    online=False,\n"
            f"    description={literal(node.get('description', '').strip())},\n"
            f'    tags={{"grain": {literal(grain)}}},\n'
            ")\n"
        )
        names.append(const)
    views = (
        "\n#: Every feature view, by mart name.\nVIEWS = (\n"
        + "".join(f"    {n},\n" for n in names)
        + ")\n"
    )
    return HEADER.format(types=", ".join(sorted(used_types))) + "".join(blocks) + views


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point.

    Parameters
    ----------
    argv : list of str, optional
        Arguments; ``sys.argv[1:]`` when omitted.

    Returns
    -------
    int
        0 on success; with ``--check``, 1 when the output file is stale.
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check", action="store_true", help="exit 1 when --output differs; write nothing"
    )
    args = parser.parse_args(argv)
    text = render(json.loads(args.manifest.read_text()))
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != text:
            print(f"{args.output} is stale: regenerate with `just feature-views`", file=sys.stderr)
            return 1
        print(f"{args.output} is current")
        return 0
    args.output.write_text(text)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
