"""Write the Feast views, the feature-value fact and the feature dimension from the dbt manifest.

Every model under ``models/features/`` becomes one ``SparkSource`` (a query
selecting its keys, ``trade_date_key``, its tagged feature columns and
``available_at``, plus ``published_at`` as the created timestamp when the
mart has one) and one ``FeatureView`` on the entities of its grain, in
``power_market_analytics/features/views.py``. The same tagged columns are
unpivoted to the period grain in the dbt model
``dbt/models/curated/fct_feature_value.sql`` (the Superset surface of the
catalogue): day marts are broadcast to the 48 periods and hour marts joined
on the period's hour through ``dim_half_hour``, every value cast to
double, and a mart with ``published_at`` keeps the newest published row per
key and ``available_at``, the row Feast serves. A generated model gives the
fact real ``ref`` edges, which a model walking ``graph`` at parse time
cannot have.

Every tagged column also declares ``meta.expression``, the name people read
(``LAG(demand_kwh, 2d)``); the column name stays the name code, Feast and
LightGBM use. The expression becomes the field's ``expression`` tag and a
row of ``dbt/models/curated/dim_feature.sql``, one row per feature, with the
retired features old runs still name (seed ``retired_features``). Column
names and expressions must each be unique across the marts. ``--check``
exits 1 when any of the three files is stale, which the ``dbt parse`` CI job
runs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "dbt" / "target" / "manifest.json"
DEFAULT_OUTPUT = REPO_ROOT / "power_market_analytics" / "features" / "views.py"
DEFAULT_FACT_OUTPUT = REPO_ROOT / "dbt" / "models" / "curated" / "fct_feature_value.sql"
DEFAULT_DIM_OUTPUT = REPO_ROOT / "dbt" / "models" / "curated" / "dim_feature.sql"
FEATURES_PATH_PREFIX = "features/"
#: The column meta key naming a feature's expression, and the field tag it becomes.
EXPRESSION_KEY = "expression"
#: dbt contract data types → Feast types.
DTYPES: dict[str, str] = {
    "int": "Int64",
    "bigint": "Int64",
    "double": "Float64",
    "string": "String",
    "boolean": "Bool",
    "timestamp": "UnixTimestamp",
}
TRADE_DATE_KEY_SQL = "cast(date_format(trade_date, 'yyyyMMdd') as int) as trade_date_key"
#: The column a mart with several vintages per key carries; Feast's tie-break on available_at.
CREATED_TIMESTAMP_COL = "published_at"
#: Contract data types the fact casts to double as they are; booleans go through int.
NUMERIC_TYPES = frozenset({"int", "bigint", "double"})
FACT_HEADER = """\
-- fct_feature_value: every tagged feature column of every feature mart,
-- unpivoted to the period grain (area_code x trade_date x time_code x
-- feature_ref x available_at). GENERATED by scripts/generate_feature_views.py
-- from dbt/target/manifest.json; do not edit. Regenerate with
-- `just feature-views` after a mart changes.
with
  periods as (
  select
    time_code,
    hour_of_day + 1 as hour_ending
  from
    {{ ref('dim_half_hour') }}
  ),
"""
FACT_FOOTER = """\
  final as (
  select
    area_code,
    trade_date,
    time_code,
    feature_view,
    feature_name,
    concat(feature_view, ':', feature_name) as feature_ref,
    feature_value,
    is_categorical,
    available_at,
    published_at
  from
    unioned
  )

select * from final
"""
DIM_HEADER = """\
-- dim_feature: one row per feature, the catalogue's names. feature_name is the
-- mart column (what code, Feast and LightGBM use, and what the contribution and
-- importance facts store); feature_expression is the name people read. Every
-- tagged column of every feature mart, then the retired features old runs still
-- name (seed retired_features). GENERATED by scripts/generate_feature_views.py
-- from dbt/target/manifest.json; do not edit. Regenerate with
-- `just feature-views` after a mart changes.
with
  marts as (
  select * from values
{% raw %}
"""
DIM_FOOTER = """\
{% endraw %}
    as t(feature_name, feature_expression, feature_view, grain, data_type, is_categorical, feature_description)
  ),

  retired as (
  select
    feature_name,
    feature_expression,
    cast(null as string) as feature_view,
    cast(null as string) as grain,
    cast(null as string) as data_type,
    cast(is_categorical as boolean) as is_categorical,
    feature_description
  from
    {{ ref('retired_features') }}
  ),

  unioned as (
  select *, false as is_retired from marts
  union all
  select *, true as is_retired from retired
  ),

  final as (
  select
    feature_name,
    feature_expression,
    feature_view,
    case when feature_view is not null then concat(feature_view, ':', feature_name) end as feature_ref,
    grain,
    data_type,
    is_categorical,
    is_retired,
    feature_description
  from
    unioned
  )

select * from final
"""
HEADER = '''"""Feast feature views over the dbt feature marts.

GENERATED by scripts/generate_feature_views.py from dbt/target/manifest.json;
do not edit. Regenerate with `just feature-views` after a mart changes.
"""

from feast import FeatureView, Field
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
from feast.types import {types}

from power_market_analytics.features.entities import GRAIN_ENTITIES
'''


def literal(text: str) -> str:
    """A double-quoted Python string literal for ``text`` (JSON escaping is a subset of Python's).

    Parameters
    ----------
    text : str

    Returns
    -------
    str
    """
    return json.dumps(text, ensure_ascii=False)


def feature_models(manifest: dict) -> list[dict]:
    """The manifest's models under ``models/features/``, by name.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    list of dict
    """
    return sorted(
        (
            node
            for node in manifest["nodes"].values()
            if node["resource_type"] == "model" and node["path"].startswith(FEATURES_PATH_PREFIX)
        ),
        key=lambda node: node["name"],
    )


def column_meta(column: dict) -> dict:
    """A column's ``meta`` (dbt 1.10 keeps it under ``config``, older manifests at the top).

    Parameters
    ----------
    column : dict

    Returns
    -------
    dict
    """
    return column.get("config", {}).get("meta") or column.get("meta") or {}


def grain_of(node: dict) -> str:
    """``period`` when the mart has ``time_code``, ``hour`` when ``hour_ending``, else ``day``.

    Parameters
    ----------
    node : dict
        A manifest model node.

    Returns
    -------
    str
    """
    columns = node["columns"]
    if "time_code" in columns:
        return "period"
    if "hour_ending" in columns:
        return "hour"
    return "day"


def tagged_columns(node: dict) -> list[dict]:
    """The columns of a manifest model node tagged ``feature``, in contract order.

    Parameters
    ----------
    node : dict

    Returns
    -------
    list of dict
    """
    return [column for column in node["columns"].values() if column_meta(column).get("feature")]


def catalogue(manifest: dict) -> list[dict]:
    """One entry per tagged feature column, by mart name then contract order.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    list of dict
        ``feature_name``, ``feature_expression``, ``feature_view``, ``grain``,
        ``data_type``, ``is_categorical`` and ``feature_description`` each.

    Raises
    ------
    ValueError
        If a tagged column declares no expression, or two tagged columns share
        a name or an expression.
    """
    entries: list[dict] = []
    for node in feature_models(manifest):
        for column in tagged_columns(node):
            meta = column_meta(column)
            expression = meta.get(EXPRESSION_KEY)
            if not isinstance(expression, str) or not expression.strip():
                raise ValueError(f"{node['name']}.{column['name']}: no meta.{EXPRESSION_KEY}")
            entries.append(
                {
                    "feature_name": column["name"],
                    "feature_expression": expression.strip(),
                    "feature_view": node["name"],
                    "grain": grain_of(node),
                    "data_type": column["data_type"],
                    "is_categorical": bool(meta.get("categorical")),
                    "feature_description": " ".join(column.get("description", "").split()),
                }
            )
    for key in ("feature_name", "feature_expression"):
        seen: dict[str, str] = {}
        for entry in entries:
            ref = f"{entry['feature_view']}.{entry['feature_name']}"
            if entry[key] in seen:
                raise ValueError(f"{ref} and {seen[entry[key]]} share the {key} {entry[key]!r}")
            seen[entry[key]] = ref
    return entries


def sql_string(text: str) -> str:
    """A single-quoted Spark SQL string literal for ``text``, backslash-escaped.

    Parameters
    ----------
    text : str

    Returns
    -------
    str
    """
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_dim(manifest: dict) -> str:
    """The ``dim_feature`` model SQL: the catalogue as literal rows, then the retired seed.

    The rows sit in a ``{% raw %}`` block, so a description can never be read
    as Jinja.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        As :func:`catalogue`, or when no mart has a tagged column.
    """
    entries = catalogue(manifest)
    if not entries:
        raise ValueError("no feature mart has a tagged column")
    rows = ",\n".join(
        "    ("
        + ", ".join(
            [
                sql_string(entry["feature_name"]),
                sql_string(entry["feature_expression"]),
                sql_string(entry["feature_view"]),
                sql_string(entry["grain"]),
                sql_string(entry["data_type"]),
                "true" if entry["is_categorical"] else "false",
                sql_string(entry["feature_description"]),
            ]
        )
        + ")"
        for entry in entries
    )
    return DIM_HEADER + rows + "\n" + DIM_FOOTER


def feature_value_sql(column: dict, mart: str) -> str:
    """The column as a double: ``cast(m.<col> as double)``, booleans through int.

    Parameters
    ----------
    column : dict
        A manifest column with ``name`` and ``data_type``.
    mart : str
        The model name, for the error.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        If the data type is neither numeric nor boolean.
    """
    dtype = column["data_type"]
    if dtype in NUMERIC_TYPES:
        return f"cast(m.{column['name']} as double)"
    if dtype == "boolean":
        return f"cast(cast(m.{column['name']} as int) as double)"
    raise ValueError(f"{mart}.{column['name']}: data type {dtype!r} has no numeric feature value")


def render_fact(manifest: dict) -> str:
    """The ``fct_feature_value`` model SQL for the manifest's feature marts.

    One CTE per mart with a tagged column: its keys, ``available_at`` and
    ``published_at`` (null where the mart has none) beside a ``stack()`` of
    ``(feature_name, feature_value, is_categorical)`` over the tagged columns;
    day marts cross-join the periods, hour marts join on the period's hour; a
    mart with ``published_at`` keeps the newest published row per key and
    ``available_at`` first. The CTEs are unioned in mart-name order.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        If a tagged column is neither numeric nor boolean, or no mart has one.
    """
    ctes: list[str] = []
    names: list[str] = []
    for node in feature_models(manifest):
        columns = tagged_columns(node)
        if not columns:
            continue
        name = node["name"]
        grain = grain_of(node)
        key = "time_code" if grain == "period" else "hour_ending" if grain == "hour" else None
        rows = ",\n".join(
            f"      '{column['name']}', {feature_value_sql(column, name)}, "
            + ("true" if column_meta(column).get("categorical") else "false")
            for column in columns
        )
        has_published = CREATED_TIMESTAMP_COL in node["columns"]
        if has_published:
            partition = ", ".join(
                ["area_code", "trade_date", *([key] if key else []), "available_at"]
            )
            source = (
                "(\n    select\n      *,\n      row_number() over (\n"
                f"        partition by {partition}\n"
                "        order by published_at desc\n      ) as vintage_rank\n"
                f"    from\n      {{{{ ref('{name}') }}}}\n    ) m"
            )
            where = "\n  where\n    m.vintage_rank = 1"
        else:
            source = f"{{{{ ref('{name}') }}}} m"
            where = ""
        join = {
            "day": "\n    cross join periods p",
            "hour": "\n    join periods p on p.hour_ending = m.hour_ending",
            "period": "",
        }[grain]
        published = "m.published_at" if has_published else "cast(null as timestamp) as published_at"
        ctes.append(
            f"  {name} as (\n"
            "  select\n"
            "    m.area_code,\n"
            "    m.trade_date,\n"
            f"    {'m' if grain == 'period' else 'p'}.time_code,\n"
            f"    '{name}' as feature_view,\n"
            "    m.available_at,\n"
            f"    {published},\n"
            "    stack(\n"
            f"      {len(columns)},\n"
            f"{rows}\n"
            "    ) as (feature_name, feature_value, is_categorical)\n"
            "  from\n"
            f"    {source}{join}{where}\n"
            "  ),\n"
        )
        names.append(name)
    if not names:
        raise ValueError("no feature mart has a tagged column")
    unioned = (
        "  unioned as (\n"
        + "\n  union all\n".join(f"  select * from {name}" for name in names)
        + "\n  ),\n"
    )
    return FACT_HEADER + "".join(ctes) + unioned + FACT_FOOTER


def render(manifest: dict) -> str:
    """The ``views.py`` module text for the manifest's feature marts.

    Parameters
    ----------
    manifest : dict
        A parsed ``manifest.json``.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        If a tagged feature column has a data type without a Feast type, or as
        :func:`catalogue`.
    """
    expressions = {
        (entry["feature_view"], entry["feature_name"]): entry["feature_expression"]
        for entry in catalogue(manifest)
    }
    used_types: set[str] = set()
    blocks: list[str] = []
    names: list[str] = []
    for node in feature_models(manifest):
        name = node["name"]
        grain = grain_of(node)
        keys = ["area_code", TRADE_DATE_KEY_SQL] + (
            ["time_code"] if grain == "period" else ["hour_ending"] if grain == "hour" else []
        )
        fields: list[str] = []
        feature_cols: list[str] = []
        for column in node["columns"].values():
            meta = column_meta(column)
            if not meta.get("feature"):
                continue
            dtype = DTYPES.get(column["data_type"])
            if dtype is None:
                raise ValueError(
                    f"{name}.{column['name']}: data type {column['data_type']!r} has no Feast type"
                )
            used_types.add(dtype)
            feature_cols.append(column["name"])
            categorical = "true" if meta.get("categorical") else "false"
            expression = expressions[(name, column["name"])]
            fields.append(
                "        Field(\n"
                f"            name={literal(column['name'])},\n"
                f"            dtype={dtype},\n"
                f"            description={literal(column.get('description', '').strip())},\n"
                f'            tags={{"categorical": {literal(categorical)}, '
                f'"{EXPRESSION_KEY}": {literal(expression)}}},\n'
                "        ),\n"
            )
        # A mart with several vintages per key and issue time (a fitted feature's
        # parameters) names the vintage's publication instant, and Feast keeps the
        # newest published row among those tied on available_at.
        created = [CREATED_TIMESTAMP_COL] if CREATED_TIMESTAMP_COL in node["columns"] else []
        query = (
            "select "
            + ", ".join([*keys, *feature_cols, "available_at", *created])
            + f" from {node['schema']}.{name}"
        )
        const = name.upper()
        blocks.append(
            f"\n{const}_SOURCE = SparkSource(\n"
            f"    name={literal(name)},\n"
            f"    query={literal(query)},\n"
            '    timestamp_field="available_at",\n'
            + (
                f"    created_timestamp_column={literal(CREATED_TIMESTAMP_COL)},\n"
                if created
                else ""
            )
            + f"    description={literal(node.get('description', '').strip())},\n"
            ")\n"
            f"{const} = FeatureView(\n"
            f"    name={literal(name)},\n"
            f"    entities=list(GRAIN_ENTITIES[{literal(grain)}]),\n"
            "    schema=[\n" + "".join(fields) + "    ],\n"
            f"    source={const}_SOURCE,\n"
            "    online=False,\n"
            f"    description={literal(node.get('description', '').strip())},\n"
            f'    tags={{"grain": {literal(grain)}}},\n'
            ")\n"
        )
        names.append(const)
    views = (
        "\n#: Every feature view, by mart name.\nVIEWS = (\n"
        + "".join(f"    {n},\n" for n in names)
        + ")\n"
    )
    return HEADER.format(types=", ".join(sorted(used_types))) + "".join(blocks) + views


def main(argv: list[str] | None = None) -> int:
    """Command-line entry point.

    Parameters
    ----------
    argv : list of str, optional
        Arguments; ``sys.argv[1:]`` when omitted.

    Returns
    -------
    int
        0 on success; with ``--check``, 1 when an output file is stale.
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="the views module")
    parser.add_argument(
        "--fact-output", type=Path, default=DEFAULT_FACT_OUTPUT, help="the fct_feature_value model"
    )
    parser.add_argument(
        "--dim-output", type=Path, default=DEFAULT_DIM_OUTPUT, help="the dim_feature model"
    )
    parser.add_argument(
        "--check", action="store_true", help="exit 1 when an output differs; write nothing"
    )
    args = parser.parse_args(argv)
    manifest = json.loads(args.manifest.read_text())
    outputs = [
        (args.output, render(manifest)),
        (args.fact_output, render_fact(manifest)),
        (args.dim_output, render_dim(manifest)),
    ]
    if args.check:
        stale = [
            path for path, text in outputs if (path.read_text() if path.exists() else "") != text
        ]
        for path in stale:
            print(f"{path} is stale: regenerate with `just feature-views`", file=sys.stderr)
        if stale:
            return 1
        for path, _ in outputs:
            print(f"{path} is current")
        return 0
    for path, text in outputs:
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
