-- dim_feature: one row per feature, the catalogue's names. feature_name is the
-- mart column (what code, Feast and LightGBM use, and what the contribution and
-- importance facts store); feature_expression is the name people read. Every
-- tagged column of every feature mart, then the retired features old runs still
-- name (seed retired_features). GENERATED by scripts/generate_feature_views.py
-- from dbt/target/manifest.json; do not edit. Regenerate with
-- `just feature-views` after a mart changes.
with
  marts as (
  select * from values
{% raw %}
    ('lag_2d_mean_demand_kwh', 'LAG(DAILY_MEAN(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'Mean of D-2\'s 48 half-hourly demand values, kWh per period. Null when D-2 is not complete.'),
    ('lag_2d_max_demand_kwh', 'LAG(DAILY_MAX(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'bigint', false, 'D-2\'s maximum half-hourly demand, kWh per period.'),
    ('lag_2d_min_demand_kwh', 'LAG(DAILY_MIN(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'bigint', false, 'D-2\'s minimum half-hourly demand, kWh per period.'),
    ('lag_2d_range_demand_kwh', 'LAG(DAILY_RANGE(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'bigint', false, 'D-2\'s maximum minus minimum half-hourly demand, kWh per period.'),
    ('lag_2d_load_factor_demand', 'LAG(DAILY_MEAN(demand_kwh) / DAILY_MAX(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'D-2\'s load factor: its mean over its maximum. Unitless.'),
    ('lag_2d_morning_mean_demand_kwh', 'LAG(DAILY_MEAN(demand_kwh, time=06:00-10:00), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'Mean of D-2\'s demand over the periods from 06:00 to 10:00 (time codes 13-20), kWh per period.'),
    ('lag_2d_afternoon_mean_demand_kwh', 'LAG(DAILY_MEAN(demand_kwh, time=13:00-17:00), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'Mean of D-2\'s demand over the periods from 13:00 to 17:00 (time codes 27-34), kWh per period.'),
    ('lag_2d_evening_mean_demand_kwh', 'LAG(DAILY_MEAN(demand_kwh, time=18:00-22:00), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'Mean of D-2\'s demand over the periods from 18:00 to 22:00 (time codes 37-44), kWh per period.'),
    ('lag_2d_peak_time_code', 'LAG(DAILY_ARGMAX(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'int', false, 'The time code (1-48) of D-2\'s highest demand; the earliest one on a tie. Numeric, not categorical: neighbouring periods are close.'),
    ('lag_2d_morning_ramp_demand_kwh', 'LAG(DAILY_TREND(demand_kwh, time=06:00-10:00), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'The least-squares slope of D-2\'s demand against time over the periods from 06:00 to 10:00 (time codes 13-20), kWh per period per hour: positive when demand rose through the window.'),
    ('lag_2d_evening_ramp_demand_kwh', 'LAG(DAILY_TREND(demand_kwh, time=18:00-22:00), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'The least-squares slope of D-2\'s demand against time over the periods from 18:00 to 22:00 (time codes 37-44), kWh per period per hour: positive when demand rose through the window.'),
    ('ewm_5d_daily_max_demand_kwh', 'EWA(DAILY_MAX(demand_kwh), gap=2d, window=5, step=1d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily maximum of D-2, D-3, D-4, D-5 and D-6 with weights 16, 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_weekly_lags_daily_max_demand_kwh', 'EWA(DAILY_MAX(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily maximum of D-7, D-14, D-21 and D-28 with weights 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_5d_minus_ewm_weekly_lags_daily_max_demand_kwh', 'EWA(DAILY_MAX(demand_kwh), gap=2d, window=5, step=1d, halflife=1) - EWA(DAILY_MAX(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'ewm_5d_daily_max_demand_kwh minus ewm_weekly_lags_daily_max_demand_kwh, kWh per period: the recent weighted daily maximum against the same weekday\'s. Null when either is.'),
    ('ewm_5d_daily_mean_demand_kwh', 'EWA(DAILY_MEAN(demand_kwh), gap=2d, window=5, step=1d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily mean of D-2, D-3, D-4, D-5 and D-6 with weights 16, 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_weekly_lags_daily_mean_demand_kwh', 'EWA(DAILY_MEAN(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily mean of D-7, D-14, D-21 and D-28 with weights 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_5d_minus_ewm_weekly_lags_daily_mean_demand_kwh', 'EWA(DAILY_MEAN(demand_kwh), gap=2d, window=5, step=1d, halflife=1) - EWA(DAILY_MEAN(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'ewm_5d_daily_mean_demand_kwh minus ewm_weekly_lags_daily_mean_demand_kwh, kWh per period: the recent weighted daily mean against the same weekday\'s. Null when either is.'),
    ('ewm_5d_daily_min_demand_kwh', 'EWA(DAILY_MIN(demand_kwh), gap=2d, window=5, step=1d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily minimum of D-2, D-3, D-4, D-5 and D-6 with weights 16, 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_weekly_lags_daily_min_demand_kwh', 'EWA(DAILY_MIN(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'Exponentially weighted mean of the daily minimum of D-7, D-14, D-21 and D-28 with weights 8, 4, 2, 1, renormalised over the complete days present, kWh per period; null when none is.'),
    ('ewm_5d_minus_ewm_weekly_lags_daily_min_demand_kwh', 'EWA(DAILY_MIN(demand_kwh), gap=2d, window=5, step=1d, halflife=1) - EWA(DAILY_MIN(demand_kwh), gap=7d, window=4, step=7d, halflife=1)', 'ftr_day_actuals', 'day', 'double', false, 'ewm_5d_daily_min_demand_kwh minus ewm_weekly_lags_daily_min_demand_kwh, kWh per period: the recent weighted daily minimum against the same weekday\'s. Null when either is.'),
    ('month', 'month', 'ftr_day_calendar', 'day', 'int', false, 'Calendar month 1-12: the strategies\' month feature.'),
    ('day_of_week', 'day_of_week', 'ftr_day_calendar', 'day', 'int', false, 'Day of week with Monday = 0 and Sunday = 6, pandas dayofweek, as the strategies use it (dim_date.day_of_week_iso - 1).'),
    ('day_type', 'day_type', 'ftr_day_calendar', 'day', 'int', true, '0 Weekday, 1 Weekend, 2 Holiday; a holiday wins over the weekend flag (research demand/R-003). A LightGBM categorical.'),
    ('special_period', 'special_period', 'ftr_day_calendar', 'day', 'int', true, 'The special period the day belongs to, the first that matches: 1 年末年始 (12/30-1/3), 2 ゴールデンウィーク (4/29-5/5), 3 お盆 (8/13-8/16), the three periods of dim_date.holiday_degree, by date, so a weekend or a 祝日 inside one takes the period; 4 any other holiday (dim_date.is_holiday), a 振替休日 on 5/6 included; 5 a sandwiched working day, one with holiday_degree 0.5 or 0.3 (one or two working days between off days); 0 none, an ordinary weekend included (feature candidate #131). A LightGBM categorical.'),
    ('holiday_degree', 'holiday_degree', 'ftr_day_calendar', 'day', 'double', false, 'dim_date.holiday_degree, the graded 休日度合い from 0 to 1 (research demand/R-005).'),
    ('half', 'half', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.half: 1 before July, else 2.'),
    ('quarter', 'quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.quarter, calendar quarter 1-4.'),
    ('day_of_month', 'day_of_month', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_month.'),
    ('day_of_quarter', 'day_of_quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_quarter.'),
    ('day_of_year', 'day_of_year', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_year.'),
    ('is_business_day', 'is_business_day', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.is_business_day as 1 / 0: a working day, not a bank day.'),
    ('fiscal_quarter', 'fiscal_quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.fiscal_quarter, April = Q1.'),
    ('days_since_holiday', 'DAYS_SINCE(is_holiday)', 'ftr_day_calendar', 'day', 'int', false, 'Calendar days since the nearest earlier named holiday (dim_date.is_holiday), 0 on a holiday; null before the spine\'s first holiday.'),
    ('days_until_holiday', 'DAYS_UNTIL(is_holiday)', 'ftr_day_calendar', 'day', 'int', false, 'Calendar days until the nearest later named holiday, 0 on a holiday; null after the spine\'s last holiday.'),
    ('max_popw_forecast_temperature_c', 'DAILY_MAX(MEAN(forecast_temperature_c, weight=population))', 'ftr_day_msm', 'day', 'double', false, 'The highest of the day\'s 24 hourly population-weighted forecast temperatures, C. Null unless all 24 hours have one.'),
    ('min_popw_forecast_temperature_c', 'DAILY_MIN(MEAN(forecast_temperature_c, weight=population))', 'ftr_day_msm', 'day', 'double', false, 'The lowest of the day\'s 24 hourly population-weighted forecast temperatures, C. Null unless all 24 hours have one.'),
    ('mean_popw_forecast_temperature_c', 'DAILY_MEAN(MEAN(forecast_temperature_c, weight=population))', 'ftr_day_msm', 'day', 'double', false, 'The mean of the day\'s 24 hourly population-weighted forecast temperatures, C, added in hour order so the value is the same on every build (the ordered_weighted_mean macro, every weight 1). Null unless all 24 hours have one.'),
    ('max_popw_forecast_temperature_hour_ending', 'DAILY_ARGMAX(MEAN(forecast_temperature_c, weight=population))', 'ftr_day_msm', 'day', 'int', false, 'The hour ending, 1-24, of the day\'s highest hourly population-weighted forecast temperature; the earliest on a tie. Null unless all 24 hours have a temperature.'),
    ('max_demand_hour_ending', 'forecast_max_demand_hour_ending', 'ftr_day_occto', 'day', 'int', false, 'Hour ending 1-24 of the forecast peak demand.'),
    ('max_demand_mw', 'forecast_max_demand_mw', 'ftr_day_occto', 'day', 'int', false, 'Forecast peak demand, MW.'),
    ('max_supply_capacity_mw', 'forecast_max_supply_capacity_mw', 'ftr_day_occto', 'day', 'int', false, 'Forecast supply capacity at the peak, MW.'),
    ('wavg_temperature_c', 'EWA(temperature_c, gap=2d, window=7, step=1d, halflife=1)', 'ftr_hour_jma_obs', 'hour', 'double', false, 'Weighted mean of the station\'s temperature at this hour on D-2..D-8, weight 0.5 ** (k - 2) for lag k, renormalised over the lags present; null when all are missing. The terms are added in lag order (D-2 first), so the value is the same on every build (the ordered_weighted_mean macro).'),
    ('forecast_temperature_c', 'forecast_temperature_c', 'ftr_hour_msm', 'hour', 'double', false, 'Forecast temperature at the area\'s representative station, C.'),
    ('popw_forecast_temperature_c', 'MEAN(forecast_temperature_c, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast temperature over the area\'s stations, C, renormalised over the stations that have a value; the terms are added in station order, so the value is the same on every build (the ordered_weighted_mean macro).'),
    ('popw_forecast_relative_humidity_pct', 'MEAN(forecast_relative_humidity_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast relative humidity, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_precipitation_mm', 'MEAN(forecast_precipitation_mm, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast precipitation over the hour, mm, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_solar_radiation_mjm2', 'MEAN(forecast_solar_radiation_mjm2, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast global solar radiation over the hour, MJ/m2, renormalised over the stations that have a value and added in station order. MJ/m2 is the unit fct_jma_weather_hourly.solar_radiation_mjm2 observes in; the fact\'s shortwave_radiation_wm2 is the same field at 1 / 0.0036 the scale.'),
    ('popw_forecast_total_cloud_cover_pct', 'MEAN(forecast_total_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast total cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_high_cloud_cover_pct', 'MEAN(forecast_high_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast high cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_middle_cloud_cover_pct', 'MEAN(forecast_middle_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast middle cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_low_cloud_cover_pct', 'MEAN(forecast_low_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast low cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_wind_speed_ms', 'MEAN(forecast_wind_speed_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast wind speed, m/s, renormalised over the stations that have a value and added in station order. A mean of speeds, so not the speed of the weighted u/v vector.'),
    ('popw_forecast_u_wind_ms', 'MEAN(forecast_u_wind_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast eastward wind component, m/s, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_v_wind_ms', 'MEAN(forecast_v_wind_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast northward wind component, m/s, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_surface_pressure_hpa', 'MEAN(forecast_surface_pressure_hpa, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast surface pressure, hPa, renormalised over the stations that have a value and added in station order. Mostly set by the stations\' altitudes; sea-level pressure is the comparable one.'),
    ('popw_forecast_sea_level_pressure_hpa', 'MEAN(forecast_sea_level_pressure_hpa, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast sea-level pressure, hPa, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_discomfort_index', 'DISCOMFORT_INDEX(MEAN(forecast_temperature_c, weight=population), MEAN(forecast_relative_humidity_pct, weight=population))', 'ftr_hour_msm', 'hour', 'double', false, 'The 不快指数 (discomfort index) of the population-weighted forecast temperature T, C, and relative humidity H, %: 0.81 T + 0.01 H (0.99 T - 14.3) + 46.3 (the discomfort_index macro; 木内 2001, 天気 48(9), eq. A1, the U.S. Weather Bureau\'s temperature-humidity index in C). The index of the two means, not the mean of the stations\' indexes. Null when either mean is null. No unit; from 15 in Hokkaido\'s coldest hour to 87 in Tokyo\'s hottest humid one, 2019-04 to 2026-09. Below 14.4 C a higher humidity lowers it.'),
    ('lag_2d_demand_kwh', 'LAG(demand_kwh, 2d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-2, kWh. Public about 00:05 on D-1.'),
    ('lag_3d_demand_kwh', 'LAG(demand_kwh, 3d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-3, kWh.'),
    ('lag_7d_demand_kwh', 'LAG(demand_kwh, 7d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-7, kWh.'),
    ('lag_9d_demand_kwh', 'LAG(demand_kwh, 9d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-9, kWh: the older side of change_2d_9d_demand_kwh.'),
    ('lag_14d_demand_kwh', 'LAG(demand_kwh, 14d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-14, kWh.'),
    ('lag_21d_demand_kwh', 'LAG(demand_kwh, 21d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-21, kWh.'),
    ('lag_28d_demand_kwh', 'LAG(demand_kwh, 28d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-28, kWh.'),
    ('mean_weekly_lags_demand_kwh', 'ROLLING_MEAN(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Mean of the D-7, D-14, D-21 and D-28 lags present, kWh; null when none is.'),
    ('ewm_weekly_lags_demand_kwh', 'EWA(demand_kwh, gap=7d, window=4, step=7d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'Exponentially weighted mean of the D-7, D-14, D-21 and D-28 lags with weights 8, 4, 2, 1, renormalised over the lags present, kWh; null when none is.'),
    ('ewstd_weekly_lags_demand_kwh', 'EWSTD(demand_kwh, gap=7d, window=4, step=7d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'Exponentially weighted standard deviation of the D-7, D-14, D-21 and D-28 lags, weights 8, 4, 2, 1, with the reliability-weight correction of pandas ewm().std(): sqrt(sum w (x - m)^2 / (V1 - V2 / V1)), where m is the weighted mean, V1 the sum of the weights and V2 the sum of their squares, over the lags present. With equal weights it is the sample standard deviation. kWh. Null with fewer than two lags.'),
    ('trend_weekly_lags_demand_kwh', 'ROLLING_TREND(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Least-squares slope of the D-7, D-14, D-21 and D-28 lags present against time in weeks, kWh per week: positive when demand in this period has been rising. With all four lags it is (3 x D-7 + D-14 - D-21 - 3 x D-28) / 10. Null with fewer than two lags.'),
    ('std_weekly_lags_demand_kwh', 'ROLLING_STD(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Sample standard deviation (n - 1 in the denominator) of the D-7, D-14, D-21 and D-28 lags present, kWh. Null with fewer than two lags.'),
    ('median_weekly_lags_demand_kwh', 'ROLLING_MEDIAN(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Median of the D-7, D-14, D-21 and D-28 lags present, kWh: the mean of the middle two when an even number is present. Null when none is.'),
    ('zscore_7d_vs_14d_28d_demand_kwh', 'ROLLING_ZSCORE(demand_kwh, 7d, gap=14d, window=3, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'How unusual D-7 was against the three weeks before it: (D-7 - mean) / s, where mean and s are the mean and sample standard deviation (n - 1 in the denominator) of the D-14, D-21 and D-28 lags present. Unitless. Null when D-7 is absent, fewer than two of the three weeks are present, or s is 0.'),
    ('change_2d_9d_demand_kwh', 'LAG(DIFF(demand_kwh, 7d), 2d)', 'ftr_period_actuals', 'period', 'bigint', false, 'The D-2 lag minus the D-9 lag, kWh: the week-on-week change of the newest complete day. Null when either is absent.'),
    ('lag_7d_adjacent_mean_demand_kwh', 'LAG(ROLLING_MEAN(demand_kwh, window=3, step=30m, center=true), 7d)', 'ftr_period_actuals', 'period', 'double', false, 'Mean of D-7\'s demand at the period before, this period and the period after, over the values present, kWh; null when none is. Robust to a small shift in the timing of the load.'),
    ('lag_7d_ramp_demand_kwh', 'LAG(DIFF(demand_kwh, 30m), 7d)', 'ftr_period_actuals', 'period', 'bigint', false, 'D-7\'s demand at this period minus at the period before, kWh: whether demand was rising or falling at this time a week ago. Null when either is absent.'),
    ('mean_weekly_lags_ramp_demand_kwh', 'ROLLING_MEAN(DIFF(demand_kwh, 30m), gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Mean of the period-to-period ramps (this period minus the period before) of D-7, D-14, D-21 and D-28, over the ramps present, kWh; null when none is.'),
    ('mean_daytype_4d_demand_kwh', 'ROLLING_MEAN(demand_kwh, gap=2d, window=4) by day_type', 'ftr_period_actuals', 'period', 'double', false, 'Mean over the same period of the last four complete days of D\'s day type (ftr_day_calendar.day_type) at or before D-2, kWh; fewer days at the start of the history; null when there is none.'),
    ('ewm_daytype_4d_demand_kwh', 'EWA(demand_kwh, gap=2d, window=4, halflife=1) by day_type', 'ftr_period_actuals', 'period', 'double', false, 'The same four days with weights 8, 4, 2, 1 from the newest back, renormalised over the days present, kWh.'),
    ('ewm_5d_demand_kwh', 'EWA(demand_kwh, gap=2d, window=5, step=1d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'Exponentially weighted mean of the D-2, D-3, D-4, D-5 and D-6 demand over the same period with weights 16, 8, 4, 2, 1, renormalised over the days present, kWh; null when none is. The part of the past week that is public at 09:30 on D-1.'),
    ('std_5d_demand_kwh', 'ROLLING_STD(demand_kwh, gap=2d, window=5, step=1d)', 'ftr_period_actuals', 'period', 'double', false, 'Sample standard deviation (n - 1 in the denominator) of the D-2, D-3, D-4, D-5 and D-6 demand over the same period, over the days present, kWh. Null with fewer than two.'),
    ('ewstd_5d_demand_kwh', 'EWSTD(demand_kwh, gap=2d, window=5, step=1d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'Exponentially weighted standard deviation of the D-2, D-3, D-4, D-5 and D-6 demand over the same period, weights 16, 8, 4, 2, 1, with the reliability-weight correction of pandas ewm().std(): sqrt(sum w (x - m)^2 / (V1 - V2 / V1)), where m is the weighted mean, V1 the sum of the weights and V2 the sum of their squares, over the lags present. With equal weights it is the sample standard deviation. kWh. Null with fewer than two lags.'),
    ('ewm_5d_minus_ewm_weekly_lags_demand_kwh', 'EWA(demand_kwh, gap=2d, window=5, step=1d, halflife=1) - EWA(demand_kwh, gap=7d, window=4, step=7d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'ewm_5d_demand_kwh minus ewm_weekly_lags_demand_kwh, kWh: the recent weighted level of this period against its weighted level on the same weekday over the last four weeks. Null when either is.'),
    ('lag_2d_over_daily_mean_demand', 'LAG(demand_kwh, 2d) / LAG(DAILY_MEAN(demand_kwh), 2d)', 'ftr_period_actuals', 'period', 'double', false, 'D-2\'s demand at the period over the mean of D-2\'s 48 periods: the shape of the day without its level, 1.0 at the day\'s average (feature candidate #137). One division, 48 x lag / the day\'s sum, so the integers stay exact. Null unless D-2 is complete, all 48 periods, or when its sum is 0.'),
    ('lag_7d_over_daily_mean_demand', 'LAG(demand_kwh, 7d) / LAG(DAILY_MEAN(demand_kwh), 7d)', 'ftr_period_actuals', 'period', 'double', false, 'D-7\'s demand at the period over the mean of D-7\'s 48 periods, as lag_2d_over_daily_mean_demand (feature candidate #137). Null unless D-7 is complete or when its sum is 0.'),
    ('lag_2d_position_28d_demand', '(LAG(demand_kwh, 2d) - ROLLING_MIN(demand_kwh, gap=2d, window=28, step=1d)) / (ROLLING_MAX(demand_kwh, gap=2d, window=28, step=1d) - ROLLING_MIN(demand_kwh, gap=2d, window=28, step=1d))', 'ftr_period_actuals', 'period', 'double', false, 'Where D-2\'s demand at the period sits between the lowest and the highest of the same period over the 28 days D-2 to D-29, the values present: 0 at the lowest, 1 at the highest (feature candidate #149). D-2 is inside the window, so the value is within 0 to 1. Null when D-2 is absent or the highest equals the lowest.'),
    ('rel_ewm_5d_minus_ewm_weekly_lags_demand', '(EWA(demand_kwh, gap=2d, window=5, step=1d, halflife=1) - EWA(demand_kwh, gap=7d, window=4, step=7d, halflife=1)) / EWA(demand_kwh, gap=7d, window=4, step=7d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'ewm_5d_minus_ewm_weekly_lags_demand_kwh over ewm_weekly_lags_demand_kwh: the recent level against the weekly one as a fraction of the weekly one, -0.05 when the last five days ran 5 % under it (feature candidate #146). A fraction, not a percentage. Null when either mean is null or the weekly one is 0.'),
    ('rel_change_2d_9d_demand', 'LAG(DIFF(demand_kwh, 7d), 2d) / LAG(demand_kwh, 9d)', 'ftr_period_actuals', 'period', 'double', false, 'change_2d_9d_demand_kwh over lag_9d_demand_kwh: the week-on-week change from D-9 to D-2 as a fraction of D-9 (feature candidate #147). A fraction, not a percentage. Null when D-2 or D-9 is absent or D-9 is 0.'),
    ('lag_7d_minus_median_weekly_lags_demand_kwh', 'LAG(demand_kwh, 7d) - ROLLING_MEDIAN(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'lag_7d_demand_kwh minus median_weekly_lags_demand_kwh, kWh: how far D-7 sits from the middle of the four weekly lags present, itself among them (feature candidate #154). Null when D-7 is absent.'),
    ('lag_1d_price', 'LAG(area_price_jpy_kwh, 1d)', 'ftr_period_jepx', 'period', 'double', false, 'Area price of the same period on D-1, JPY/kWh.'),
    ('similar_day_rank1_demand_kwh', 'SIMILAR_DAY(power_usage_demand_kwh, gap=(2d, 335d), window=(30, 60), rank=1, holidays=last_year) / 2', 'ftr_period_similar_day', 'period', 'double', false, 'The nearest pool day\'s hourly load (fct_area_power_usage_hourly, kWh over the hour containing the period) halved, kWh per 30-minute period. On a same-holiday day, the load of last year\'s same holiday. Never null.'),
    ('similar_day_rank2_demand_kwh', 'SIMILAR_DAY(power_usage_demand_kwh, gap=(2d, 335d), window=(30, 60), rank=2, holidays=last_year) / 2', 'ftr_period_similar_day', 'period', 'double', false, 'The second nearest pool day\'s hourly load (fct_area_power_usage_hourly, kWh over the hour containing the period) halved, kWh per 30-minute period. Null on a same-holiday day and when the pool has fewer than two days.'),
    ('similar_day_rank3_demand_kwh', 'SIMILAR_DAY(power_usage_demand_kwh, gap=(2d, 335d), window=(30, 60), rank=3, holidays=last_year) / 2', 'ftr_period_similar_day', 'period', 'double', false, 'The third nearest pool day\'s hourly load (fct_area_power_usage_hourly, kWh over the hour containing the period) halved, kWh per 30-minute period. Null on a same-holiday day and when the pool has fewer than three days.'),
    ('wavg_similar_day_top3_demand_kwh', 'SIMILAR_DAY_MEAN(power_usage_demand_kwh, gap=(2d, 335d), window=(30, 60), k=3, weight=inverse_distance, holidays=last_year) / 2', 'ftr_period_similar_day', 'period', 'double', false, 'The mean of the three nearest pool days\' hourly loads halved, weighted by inverse distance (w_r = (1 / d_r) / sum_s (1 / d_s) over the ranks present, summed in rank order; days at distance 0 share all the weight), kWh per 30-minute period. On a same-holiday day, rank 1\'s load. Never null.')
{% endraw %}
    as t(feature_name, feature_expression, feature_view, grain, data_type, is_categorical, feature_description)
  ),

  retired as (
  select
    feature_name,
    feature_expression,
    cast(null as string) as feature_view,
    cast(null as string) as grain,
    cast(null as string) as data_type,
    cast(is_categorical as boolean) as is_categorical,
    feature_description
  from
    {{ ref('retired_features') }}
  ),

  unioned as (
  select *, false as is_retired from marts
  union all
  select *, true as is_retired from retired
  ),

  final as (
  select
    feature_name,
    feature_expression,
    feature_view,
    case when feature_view is not null then concat(feature_view, ':', feature_name) end as feature_ref,
    grain,
    data_type,
    is_categorical,
    is_retired,
    feature_description
  from
    unioned
  )

select * from final
