-- dim_feature: one row per feature, the catalogue's names. feature_name is the
-- mart column (what code, Feast and LightGBM use, and what the contribution and
-- importance facts store); feature_expression is the name people read. Every
-- tagged column of every feature mart, then the retired features old runs still
-- name (seed retired_features). GENERATED by scripts/generate_feature_views.py
-- from dbt/target/manifest.json; do not edit. Regenerate with
-- `just feature-views` after a mart changes.
with
  marts as (
  select * from values
{% raw %}
    ('lag_2d_mean_demand_kwh', 'LAG(DAILY_MEAN(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'double', false, 'Mean of D-2\'s 48 half-hourly demand values, kWh per period.'),
    ('lag_2d_max_demand_kwh', 'LAG(DAILY_MAX(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'bigint', false, 'D-2\'s maximum half-hourly demand, kWh per period.'),
    ('lag_2d_range_demand_kwh', 'LAG(DAILY_RANGE(demand_kwh), 2d)', 'ftr_day_actuals', 'day', 'bigint', false, 'D-2\'s maximum minus minimum half-hourly demand, kWh per period.'),
    ('month', 'month', 'ftr_day_calendar', 'day', 'int', false, 'Calendar month 1-12: the strategies\' month feature.'),
    ('day_of_week', 'day_of_week', 'ftr_day_calendar', 'day', 'int', false, 'Day of week with Monday = 0 and Sunday = 6, pandas dayofweek, as the strategies use it (dim_date.day_of_week_iso - 1).'),
    ('day_type', 'day_type', 'ftr_day_calendar', 'day', 'int', true, '0 Weekday, 1 Weekend, 2 Holiday; a holiday wins over the weekend flag (research demand/R-003). A LightGBM categorical.'),
    ('holiday_degree', 'holiday_degree', 'ftr_day_calendar', 'day', 'double', false, 'dim_date.holiday_degree, the graded 休日度合い from 0 to 1 (research demand/R-005).'),
    ('half', 'half', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.half: 1 before July, else 2.'),
    ('quarter', 'quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.quarter, calendar quarter 1-4.'),
    ('day_of_month', 'day_of_month', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_month.'),
    ('day_of_quarter', 'day_of_quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_quarter.'),
    ('day_of_year', 'day_of_year', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.day_of_year.'),
    ('is_business_day', 'is_business_day', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.is_business_day as 1 / 0: a working day, not a bank day.'),
    ('fiscal_quarter', 'fiscal_quarter', 'ftr_day_calendar', 'day', 'int', false, 'dim_date.fiscal_quarter, April = Q1.'),
    ('days_since_holiday', 'DAYS_SINCE(is_holiday)', 'ftr_day_calendar', 'day', 'int', false, 'Calendar days since the nearest earlier named holiday (dim_date.is_holiday), 0 on a holiday; null before the spine\'s first holiday.'),
    ('days_until_holiday', 'DAYS_UNTIL(is_holiday)', 'ftr_day_calendar', 'day', 'int', false, 'Calendar days until the nearest later named holiday, 0 on a holiday; null after the spine\'s last holiday.'),
    ('max_demand_hour_ending', 'forecast_max_demand_hour_ending', 'ftr_day_occto', 'day', 'int', false, 'Hour ending 1-24 of the forecast peak demand.'),
    ('max_demand_mw', 'forecast_max_demand_mw', 'ftr_day_occto', 'day', 'int', false, 'Forecast peak demand, MW.'),
    ('max_supply_capacity_mw', 'forecast_max_supply_capacity_mw', 'ftr_day_occto', 'day', 'int', false, 'Forecast supply capacity at the peak, MW.'),
    ('wavg_temperature_c', 'EWA(temperature_c, gap=2d, window=7, step=1d, halflife=1)', 'ftr_hour_jma_obs', 'hour', 'double', false, 'Weighted mean of the station\'s temperature at this hour on D-2..D-8, weight 0.5 ** (k - 2) for lag k, renormalised over the lags present; null when all are missing. The terms are added in lag order (D-2 first), so the value is the same on every build (the ordered_weighted_mean macro).'),
    ('forecast_temperature_c', 'forecast_temperature_c', 'ftr_hour_msm', 'hour', 'double', false, 'Forecast temperature at the area\'s representative station, C.'),
    ('popw_forecast_temperature_c', 'WEIGHTED_MEAN(forecast_temperature_c, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast temperature over the area\'s stations, C, renormalised over the stations that have a value; the terms are added in station order, so the value is the same on every build (the ordered_weighted_mean macro).'),
    ('popw_forecast_relative_humidity_pct', 'WEIGHTED_MEAN(forecast_relative_humidity_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast relative humidity, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_precipitation_mm', 'WEIGHTED_MEAN(forecast_precipitation_mm, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast precipitation over the hour, mm, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_solar_radiation_mjm2', 'WEIGHTED_MEAN(forecast_solar_radiation_mjm2, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast global solar radiation over the hour, MJ/m2, renormalised over the stations that have a value and added in station order. MJ/m2 is the unit fct_jma_weather_hourly.solar_radiation_mjm2 observes in; the fact\'s shortwave_radiation_wm2 is the same field at 1 / 0.0036 the scale.'),
    ('popw_forecast_total_cloud_cover_pct', 'WEIGHTED_MEAN(forecast_total_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast total cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_high_cloud_cover_pct', 'WEIGHTED_MEAN(forecast_high_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast high cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_middle_cloud_cover_pct', 'WEIGHTED_MEAN(forecast_middle_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast middle cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_low_cloud_cover_pct', 'WEIGHTED_MEAN(forecast_low_cloud_cover_pct, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast low cloud cover, %, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_wind_speed_ms', 'WEIGHTED_MEAN(forecast_wind_speed_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast wind speed, m/s, renormalised over the stations that have a value and added in station order. A mean of speeds, so not the speed of the weighted u/v vector.'),
    ('popw_forecast_u_wind_ms', 'WEIGHTED_MEAN(forecast_u_wind_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast eastward wind component, m/s, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_v_wind_ms', 'WEIGHTED_MEAN(forecast_v_wind_ms, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast northward wind component, m/s, renormalised over the stations that have a value and added in station order.'),
    ('popw_forecast_surface_pressure_hpa', 'WEIGHTED_MEAN(forecast_surface_pressure_hpa, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast surface pressure, hPa, renormalised over the stations that have a value and added in station order. Mostly set by the stations\' altitudes; sea-level pressure is the comparable one.'),
    ('popw_forecast_sea_level_pressure_hpa', 'WEIGHTED_MEAN(forecast_sea_level_pressure_hpa, weight=population)', 'ftr_hour_msm', 'hour', 'double', false, 'Population-weighted forecast sea-level pressure, hPa, renormalised over the stations that have a value and added in station order.'),
    ('lag_2d_demand_kwh', 'LAG(demand_kwh, 2d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-2, kWh. Public about 00:05 on D-1.'),
    ('lag_3d_demand_kwh', 'LAG(demand_kwh, 3d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-3, kWh.'),
    ('lag_7d_demand_kwh', 'LAG(demand_kwh, 7d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-7, kWh.'),
    ('lag_9d_demand_kwh', 'LAG(demand_kwh, 9d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-9, kWh: the older side of change_2d_9d_demand_kwh.'),
    ('lag_14d_demand_kwh', 'LAG(demand_kwh, 14d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-14, kWh.'),
    ('lag_21d_demand_kwh', 'LAG(demand_kwh, 21d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-21, kWh.'),
    ('lag_28d_demand_kwh', 'LAG(demand_kwh, 28d)', 'ftr_period_actuals', 'period', 'bigint', false, 'Area demand over the same period on D-28, kWh.'),
    ('mean_weekly_lags_demand_kwh', 'ROLLING_MEAN(demand_kwh, gap=7d, window=4, step=7d)', 'ftr_period_actuals', 'period', 'double', false, 'Mean of the D-7, D-14, D-21 and D-28 lags present, kWh; null when none is.'),
    ('ewm_weekly_lags_demand_kwh', 'EWA(demand_kwh, gap=7d, window=4, step=7d, halflife=1)', 'ftr_period_actuals', 'period', 'double', false, 'Exponentially weighted mean of the D-7, D-14, D-21 and D-28 lags with weights 8, 4, 2, 1, renormalised over the lags present, kWh; null when none is.'),
    ('change_2d_9d_demand_kwh', 'LAG(DIFF(demand_kwh, 7d), 2d)', 'ftr_period_actuals', 'period', 'bigint', false, 'The D-2 lag minus the D-9 lag, kWh: the week-on-week change of the newest complete day. Null when either is absent.'),
    ('mean_daytype_4d_demand_kwh', 'ROLLING_MEAN(demand_kwh, gap=2d, window=4) by day_type', 'ftr_period_actuals', 'period', 'double', false, 'Mean over the same period of the last four complete days of D\'s day type (ftr_day_calendar.day_type) at or before D-2, kWh; fewer days at the start of the history; null when there is none.'),
    ('ewm_daytype_4d_demand_kwh', 'EWA(demand_kwh, gap=2d, window=4, halflife=1) by day_type', 'ftr_period_actuals', 'period', 'double', false, 'The same four days with weights 8, 4, 2, 1 from the newest back, renormalised over the days present, kWh.'),
    ('lag_1d_price', 'LAG(area_price_jpy_kwh, 1d)', 'ftr_period_jepx', 'period', 'double', false, 'Area price of the same period on D-1, JPY/kWh.'),
    ('similar_day_demand_kwh', 'SIMILAR_DAY(power_usage_demand_kwh, gap=334d, window=61) / 2', 'ftr_period_similar_day', 'period', 'double', false, 'The chosen similar day\'s hourly load (fct_area_power_usage_hourly, kWh over the hour containing the period) halved, kWh per 30-minute period.')
{% endraw %}
    as t(feature_name, feature_expression, feature_view, grain, data_type, is_categorical, feature_description)
  ),

  retired as (
  select
    feature_name,
    feature_expression,
    cast(null as string) as feature_view,
    cast(null as string) as grain,
    cast(null as string) as data_type,
    cast(is_categorical as boolean) as is_categorical,
    feature_description
  from
    {{ ref('retired_features') }}
  ),

  unioned as (
  select *, false as is_retired from marts
  union all
  select *, true as is_retired from retired
  ),

  final as (
  select
    feature_name,
    feature_expression,
    feature_view,
    case when feature_view is not null then concat(feature_view, ':', feature_name) end as feature_ref,
    grain,
    data_type,
    is_categorical,
    is_retired,
    feature_description
  from
    unioned
  )

select * from final
