-- fct_feature_value: every tagged feature column of every feature mart,
-- unpivoted to the period grain (area_code x trade_date x time_code x
-- feature_ref x available_at). GENERATED by scripts/generate_feature_views.py
-- from dbt/target/manifest.json; do not edit. Regenerate with
-- `just feature-views` after a mart changes.
with
  periods as (
  select
    time_code,
    hour_of_day + 1 as hour_ending
  from
    {{ ref('dim_half_hour') }}
  ),
  ftr_day_actuals as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_day_actuals' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      20,
      'lag_2d_mean_demand_kwh', cast(m.lag_2d_mean_demand_kwh as double), false,
      'lag_2d_max_demand_kwh', cast(m.lag_2d_max_demand_kwh as double), false,
      'lag_2d_min_demand_kwh', cast(m.lag_2d_min_demand_kwh as double), false,
      'lag_2d_range_demand_kwh', cast(m.lag_2d_range_demand_kwh as double), false,
      'lag_2d_load_factor_demand', cast(m.lag_2d_load_factor_demand as double), false,
      'lag_2d_morning_mean_demand_kwh', cast(m.lag_2d_morning_mean_demand_kwh as double), false,
      'lag_2d_afternoon_mean_demand_kwh', cast(m.lag_2d_afternoon_mean_demand_kwh as double), false,
      'lag_2d_evening_mean_demand_kwh', cast(m.lag_2d_evening_mean_demand_kwh as double), false,
      'lag_2d_peak_time_code', cast(m.lag_2d_peak_time_code as double), false,
      'lag_2d_morning_ramp_demand_kwh', cast(m.lag_2d_morning_ramp_demand_kwh as double), false,
      'lag_2d_evening_ramp_demand_kwh', cast(m.lag_2d_evening_ramp_demand_kwh as double), false,
      'ewm_5d_daily_max_demand_kwh', cast(m.ewm_5d_daily_max_demand_kwh as double), false,
      'ewm_weekly_lags_daily_max_demand_kwh', cast(m.ewm_weekly_lags_daily_max_demand_kwh as double), false,
      'ewm_5d_minus_ewm_weekly_lags_daily_max_demand_kwh', cast(m.ewm_5d_minus_ewm_weekly_lags_daily_max_demand_kwh as double), false,
      'ewm_5d_daily_mean_demand_kwh', cast(m.ewm_5d_daily_mean_demand_kwh as double), false,
      'ewm_weekly_lags_daily_mean_demand_kwh', cast(m.ewm_weekly_lags_daily_mean_demand_kwh as double), false,
      'ewm_5d_minus_ewm_weekly_lags_daily_mean_demand_kwh', cast(m.ewm_5d_minus_ewm_weekly_lags_daily_mean_demand_kwh as double), false,
      'ewm_5d_daily_min_demand_kwh', cast(m.ewm_5d_daily_min_demand_kwh as double), false,
      'ewm_weekly_lags_daily_min_demand_kwh', cast(m.ewm_weekly_lags_daily_min_demand_kwh as double), false,
      'ewm_5d_minus_ewm_weekly_lags_daily_min_demand_kwh', cast(m.ewm_5d_minus_ewm_weekly_lags_daily_min_demand_kwh as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_day_actuals') }} m
    cross join periods p
  ),
  ftr_day_calendar as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_day_calendar' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      17,
      'month', cast(m.month as double), false,
      'day_of_week', cast(m.day_of_week as double), false,
      'day_type', cast(m.day_type as double), true,
      'special_period', cast(m.special_period as double), true,
      'lag_2d_day_type', cast(m.lag_2d_day_type as double), true,
      'lag_3d_day_type', cast(m.lag_3d_day_type as double), true,
      'lag_7d_day_type', cast(m.lag_7d_day_type as double), true,
      'holiday_degree', cast(m.holiday_degree as double), false,
      'half', cast(m.half as double), false,
      'quarter', cast(m.quarter as double), false,
      'day_of_month', cast(m.day_of_month as double), false,
      'day_of_quarter', cast(m.day_of_quarter as double), false,
      'day_of_year', cast(m.day_of_year as double), false,
      'is_business_day', cast(m.is_business_day as double), false,
      'fiscal_quarter', cast(m.fiscal_quarter as double), false,
      'days_since_holiday', cast(m.days_since_holiday as double), false,
      'days_until_holiday', cast(m.days_until_holiday as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_day_calendar') }} m
    cross join periods p
  ),
  ftr_day_msm as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_day_msm' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      5,
      'max_popw_forecast_temperature_c', cast(m.max_popw_forecast_temperature_c as double), false,
      'min_popw_forecast_temperature_c', cast(m.min_popw_forecast_temperature_c as double), false,
      'mean_popw_forecast_temperature_c', cast(m.mean_popw_forecast_temperature_c as double), false,
      'max_popw_forecast_temperature_hour_ending', cast(m.max_popw_forecast_temperature_hour_ending as double), false,
      'morning_trend_popw_forecast_temperature_c', cast(m.morning_trend_popw_forecast_temperature_c as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_day_msm') }} m
    cross join periods p
  ),
  ftr_day_occto as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_day_occto' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      3,
      'max_demand_hour_ending', cast(m.max_demand_hour_ending as double), false,
      'max_demand_mw', cast(m.max_demand_mw as double), false,
      'max_supply_capacity_mw', cast(m.max_supply_capacity_mw as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_day_occto') }} m
    cross join periods p
  ),
  ftr_hour_jma_obs as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_hour_jma_obs' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      4,
      'wavg_temperature_c', cast(m.wavg_temperature_c as double), false,
      'mean_24h_popw_temperature_c', cast(m.mean_24h_popw_temperature_c as double), false,
      'mean_72h_popw_temperature_c', cast(m.mean_72h_popw_temperature_c as double), false,
      'ewm_72h_popw_temperature_c', cast(m.ewm_72h_popw_temperature_c as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_hour_jma_obs') }} m
    join periods p on p.hour_ending = m.hour_ending
  ),
  ftr_hour_msm as (
  select
    m.area_code,
    m.trade_date,
    p.time_code,
    'ftr_hour_msm' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      16,
      'forecast_temperature_c', cast(m.forecast_temperature_c as double), false,
      'popw_forecast_temperature_c', cast(m.popw_forecast_temperature_c as double), false,
      'popw_forecast_relative_humidity_pct', cast(m.popw_forecast_relative_humidity_pct as double), false,
      'popw_forecast_precipitation_mm', cast(m.popw_forecast_precipitation_mm as double), false,
      'popw_forecast_solar_radiation_mjm2', cast(m.popw_forecast_solar_radiation_mjm2 as double), false,
      'popw_forecast_total_cloud_cover_pct', cast(m.popw_forecast_total_cloud_cover_pct as double), false,
      'popw_forecast_high_cloud_cover_pct', cast(m.popw_forecast_high_cloud_cover_pct as double), false,
      'popw_forecast_middle_cloud_cover_pct', cast(m.popw_forecast_middle_cloud_cover_pct as double), false,
      'popw_forecast_low_cloud_cover_pct', cast(m.popw_forecast_low_cloud_cover_pct as double), false,
      'popw_forecast_wind_speed_ms', cast(m.popw_forecast_wind_speed_ms as double), false,
      'popw_forecast_u_wind_ms', cast(m.popw_forecast_u_wind_ms as double), false,
      'popw_forecast_v_wind_ms', cast(m.popw_forecast_v_wind_ms as double), false,
      'popw_forecast_surface_pressure_hpa', cast(m.popw_forecast_surface_pressure_hpa as double), false,
      'popw_forecast_sea_level_pressure_hpa', cast(m.popw_forecast_sea_level_pressure_hpa as double), false,
      'popw_forecast_discomfort_index', cast(m.popw_forecast_discomfort_index as double), false,
      'cum_popw_forecast_solar_radiation_mjm2', cast(m.cum_popw_forecast_solar_radiation_mjm2 as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_hour_msm') }} m
    join periods p on p.hour_ending = m.hour_ending
  ),
  ftr_period_actuals as (
  select
    m.area_code,
    m.trade_date,
    m.time_code,
    'ftr_period_actuals' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      32,
      'lag_2d_demand_kwh', cast(m.lag_2d_demand_kwh as double), false,
      'lag_3d_demand_kwh', cast(m.lag_3d_demand_kwh as double), false,
      'lag_7d_demand_kwh', cast(m.lag_7d_demand_kwh as double), false,
      'lag_9d_demand_kwh', cast(m.lag_9d_demand_kwh as double), false,
      'lag_14d_demand_kwh', cast(m.lag_14d_demand_kwh as double), false,
      'lag_21d_demand_kwh', cast(m.lag_21d_demand_kwh as double), false,
      'lag_28d_demand_kwh', cast(m.lag_28d_demand_kwh as double), false,
      'mean_weekly_lags_demand_kwh', cast(m.mean_weekly_lags_demand_kwh as double), false,
      'ewm_weekly_lags_demand_kwh', cast(m.ewm_weekly_lags_demand_kwh as double), false,
      'ewstd_weekly_lags_demand_kwh', cast(m.ewstd_weekly_lags_demand_kwh as double), false,
      'trend_weekly_lags_demand_kwh', cast(m.trend_weekly_lags_demand_kwh as double), false,
      'std_weekly_lags_demand_kwh', cast(m.std_weekly_lags_demand_kwh as double), false,
      'median_weekly_lags_demand_kwh', cast(m.median_weekly_lags_demand_kwh as double), false,
      'zscore_7d_vs_14d_28d_demand_kwh', cast(m.zscore_7d_vs_14d_28d_demand_kwh as double), false,
      'change_2d_9d_demand_kwh', cast(m.change_2d_9d_demand_kwh as double), false,
      'lag_7d_adjacent_mean_demand_kwh', cast(m.lag_7d_adjacent_mean_demand_kwh as double), false,
      'lag_7d_ramp_demand_kwh', cast(m.lag_7d_ramp_demand_kwh as double), false,
      'mean_weekly_lags_ramp_demand_kwh', cast(m.mean_weekly_lags_ramp_demand_kwh as double), false,
      'mean_daytype_4d_demand_kwh', cast(m.mean_daytype_4d_demand_kwh as double), false,
      'ewm_daytype_4d_demand_kwh', cast(m.ewm_daytype_4d_demand_kwh as double), false,
      'ewm_5d_demand_kwh', cast(m.ewm_5d_demand_kwh as double), false,
      'std_5d_demand_kwh', cast(m.std_5d_demand_kwh as double), false,
      'ewstd_5d_demand_kwh', cast(m.ewstd_5d_demand_kwh as double), false,
      'ewm_5d_minus_ewm_weekly_lags_demand_kwh', cast(m.ewm_5d_minus_ewm_weekly_lags_demand_kwh as double), false,
      'lag_2d_over_daily_mean_demand', cast(m.lag_2d_over_daily_mean_demand as double), false,
      'lag_7d_over_daily_mean_demand', cast(m.lag_7d_over_daily_mean_demand as double), false,
      'lag_2d_position_28d_demand', cast(m.lag_2d_position_28d_demand as double), false,
      'rel_ewm_5d_minus_ewm_weekly_lags_demand', cast(m.rel_ewm_5d_minus_ewm_weekly_lags_demand as double), false,
      'rel_change_2d_9d_demand', cast(m.rel_change_2d_9d_demand as double), false,
      'lag_7d_minus_median_weekly_lags_demand_kwh', cast(m.lag_7d_minus_median_weekly_lags_demand_kwh as double), false,
      'lag_2d_wind_solar_generation_kwh', cast(m.lag_2d_wind_solar_generation_kwh as double), false,
      'lag_7d_wind_solar_generation_kwh', cast(m.lag_7d_wind_solar_generation_kwh as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_period_actuals') }} m
  ),
  ftr_period_jepx as (
  select
    m.area_code,
    m.trade_date,
    m.time_code,
    'ftr_period_jepx' as feature_view,
    m.available_at,
    cast(null as timestamp) as published_at,
    stack(
      1,
      'lag_1d_price', cast(m.lag_1d_price as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    {{ ref('ftr_period_jepx') }} m
  ),
  ftr_period_similar_day as (
  select
    m.area_code,
    m.trade_date,
    m.time_code,
    'ftr_period_similar_day' as feature_view,
    m.available_at,
    m.published_at,
    stack(
      6,
      'similar_day_rank1_demand_kwh', cast(m.similar_day_rank1_demand_kwh as double), false,
      'similar_day_rank2_demand_kwh', cast(m.similar_day_rank2_demand_kwh as double), false,
      'similar_day_rank3_demand_kwh', cast(m.similar_day_rank3_demand_kwh as double), false,
      'wavg_similar_day_top3_demand_kwh', cast(m.wavg_similar_day_top3_demand_kwh as double), false,
      'similar_day_rank1_distance', cast(m.similar_day_rank1_distance as double), false,
      'similar_day_rank1_lag_days', cast(m.similar_day_rank1_lag_days as double), false
    ) as (feature_name, feature_value, is_categorical)
  from
    (
    select
      *,
      row_number() over (
        partition by area_code, trade_date, time_code, available_at
        order by published_at desc
      ) as vintage_rank
    from
      {{ ref('ftr_period_similar_day') }}
    ) m
  where
    m.vintage_rank = 1
  ),
  unioned as (
  select * from ftr_day_actuals
  union all
  select * from ftr_day_calendar
  union all
  select * from ftr_day_msm
  union all
  select * from ftr_day_occto
  union all
  select * from ftr_hour_jma_obs
  union all
  select * from ftr_hour_msm
  union all
  select * from ftr_period_actuals
  union all
  select * from ftr_period_jepx
  union all
  select * from ftr_period_similar_day
  ),
  final as (
  select
    area_code,
    trade_date,
    time_code,
    feature_view,
    feature_name,
    concat(feature_view, ':', feature_name) as feature_ref,
    feature_value,
    is_categorical,
    available_at,
    published_at
  from
    unioned
  )

select * from final
